### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#154]
**Issuer**: David Fernandez 

**Reason**: Release current develop branch to continue development in smaller iterations

**Start date / End date**: 16/07/2017 16:30 - TBC

**Type of change**: Patch release (regardless of being called 1.0)

**Git tag reference / Release notes**: TBC

**Risk**: Very low. Nobody using prod, no database changes involved.

**Implementation plan/checklist**:

- [x] Merge all changes into `develop` branch. Rebase `develop` branch onto `master`
- [x] Deploy develop branch in DEV
- [x] Sign off current load tests (Registration, LoadAppHome) with empty DB in DEV. Save results into `results.md` with current date
- [x] Log into prod servers, upgrade Ubuntu distribution one at a time (prd01, prd02). Restart the servers, one at a time.
- [x] Implement #142, by changing the IP address for databases stored in CircleCI
- [x] Once the servers are upgraded. Merge `develop` branch into `master` and push. This will trigger CircleCI deployment into prod. Monitor the build and the load balancer at http://prdlb.graffitab.com:1936
- [x] Implement #140, which requires a restart of both prd01, prd02

**Post implementation plan**:
- [x] Ensure both app servers are green state from LB
- [x] Smoke tests using Graffitab app in prod: login, create streamable, follow, unfollow, upload avatar/cover... Test new functionality, specifically uploading assets

**Back out plan**:

- As no DB changes are involved, rolling back to a previous version would be just building previous tag `v0.1.1`
