### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#161]
**Issuer:** David Fernandez

**Reason:** Release integrations with DeviantArt & Flickr to run in production.

**Start date / End date:** 20/09/2017 20:30

**Type of change:** Feature release (see release notes)

**Git tag reference/Release notes:** TBC

**Risk:** Low. No one uses prod, but this release has several database changes.

**Implementation plan/checklist:**

- [x] Merge all changes into develop branch. Rebase develop branch onto master
- [x] Deploy develop branch in DEV
- [x] Sign off current load tests (Registration, LoadAppHome) with empty DB in DEV. Save results into results.md with current date
- [x] Deploy master branch in PROD. For that merge `develop` into `master` and push. This will trigger CircleCI deployment into prod. Monitor the build and the load balancer at http://prdlb.graffitab.com:1936
- [x] In Gitlab project `graffitab-utils` master branch, change `GRAFFITAB_URL` parameter from `https://dev.graffitab.com` to `https://www.graffitab.com`
- [x] Deploy lambda functions to AWS projects using environment `prod` instead of `staging`

**Post implementation plan:**

- [x]  Check new users `deviantart` and `flickr` being created in the DB. Ensure the `is_recommended` flag is set. Test `/whotofollow` endpoint
- [x] Upload a cover and avatar to each of the previous accounts
- [x] Check in AWS UI that the lambda function were created properly. Test a manual launch of one of them
- [x] Add Cloudwatch alarms for Flickr / DeviantArt in PROD
- [x] Monitor during some days if content is imported into production

**Comment by 8masterofpuppets8** [comment]
Looks like this works nicely! I've been monitoring it for the last few days - Flickr has 142 posts and DeviantArt 102. Lets close this release ;)
